services:
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html
      - ./config/ssl/certificate.crt:/opt/openresty/nginx/conf/ssl/certificate.crt
      - ./config/ssl/private.key:/opt/openresty/nginx/conf/ssl/private.key
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/nginx.conf:/opt/openresty/nginx/conf/nginx.conf
      - ./config/security_headers.conf:/opt/openresty/nginx/conf/security_headers.conf
      - ./config/ssl_common.conf:/opt/openresty/nginx/conf/ssl_common.conf

  db:
    image: bitnami/mariadb:11.8.2
    container_name: db
    restart: always
    environment:
      - MARIADB_HOST=db
      - MARIADB_USER=db_owpfpm
      - MARIADB_DATABASE=db_owpfpm
      - MARIADB_ROOT_PASSWORD=Gc4H2msNvV9JA4ALua
      - MARIADB_PASSWORD=Gc4H2msNvV9JA4ALua
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - backend
      
volumes:
  mariadb_data: {}


networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.1.0/24

