services:
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html
  db:
    image: mariadb:10.5.6
    container_name: db
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Gc4H2msNvV9JA4ALua
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - /log/grafana:/var/log
      - ./config/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
volumes:
  wordpress_db: {}
