services:
  web:
    build: .
    container_name: web
    restart: always
    environment:
      - ENABLE_SSL=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./html:/var/www/html
      - ./config/ssl/certificate.crt:/opt/openresty/nginx/conf/ssl/certificate.crt
      - ./config/ssl/private.key:/opt/openresty/nginx/conf/ssl/private.key
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/nginx.conf:/opt/openresty/nginx/conf/nginx.conf
      - ./config/owpfpm:/opt/openresty/nginx/conf/owpfpm
    networks:
      - frontend
      - backend  # ✅ เพิ่ม backend network เพื่อให้มองเห็น db
  db:
    image: mariadb:11.8.2
    container_name: db
    restart: always
    environment:
      MARIADB_HOST: db
      MARIADB_USER: db_owpfpm
      MARIADB_DATABASE: db_owpfpm
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
secrets:
  db_root_password:
    file: ./config/secrets/db_root_password.txt
  db_user_password:
    file: ./config/secrets/db_user_password.txt
volumes:
  mariadb_data: {}
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24

  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.1.0/24

