services:
  web:
    build:
      context: ./openresty
    container_name: web
    restart: always
    environment:
      - ENABLE_SSL=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/ssl/certificate.crt:/opt/openresty/nginx/conf/ssl/certificate.crt
      - ./config/ssl/private.key:/opt/openresty/nginx/conf/ssl/private.key
      - ./openresty/config/nginx.conf:/opt/openresty/nginx/conf/nginx.conf
      - ./openresty/config/owpfpm:/opt/openresty/nginx/conf/owpfpm
      - ./logs/openresty:/opt/openresty/nginx/logs
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php-fpm:/var/log/php-fpm
    depends_on:
      - db
    networks:
      - backend
  db:
    image: mariadb:11.8.2
    container_name: db
    restart: always
    environment:
      MARIADB_HOST: db
      MARIADB_USER_FILE: /run/secrets/db_name
      MARIADB_DATABASE_FILE: /run/secrets/db_name
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
      - db_name
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
    networks:
      - backend

secrets:
  db_root_password:
    file: ./config/secrets/db_root_password.txt
  db_user_password:
    file: ./config/secrets/db_user_password.txt
  db_name:
    file: ./config/secrets/db_name.txt

volumes:
  mariadb_data: {}

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/24
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.1.0/24