ssl_certificate     /opt/openresty/nginx/conf/ssl/certificate.crt;
ssl_certificate_key /opt/openresty/nginx/conf/ssl/private.key;
#ssl_protocols       TLSv1.2 TLSv1.3;
#ssl_prefer_server_ciphers on;
#ssl_ciphers         HIGH:!aNULL:!MD5;

# ปิด TLS 1.0 และ 1.1 (ซึ่งเป็นต้นเหตุของ weak Cipher) ให้เหลือแค่ 1.2 และ 1.3
ssl_protocols TLSv1.2 TLSv1.3;

# กำหนดให้ใช้เฉพาะ Cipher Suites ที่มีความปลอดภัยสูง
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

# ปิดการให้ความสำคัญกับ Cipher ของเซิร์ฟเวอร์เหนือไคลเอนต์ (แนะนำสำหรับ TLS 1.2/1.3)
ssl_prefer_server_ciphers off;
